// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: chXu7hBfQdWEV39yj794kD
// Component: gEcmG8cTRmM4
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_portfolio.module.css"; // plasmic-import: chXu7hBfQdWEV39yj794kD/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: gEcmG8cTRmM4/css
import Ellipse2Icon from "./icons/PlasmicIcon__Ellipse2"; // plasmic-import: eGcbCrOycP/icon
import Ellipse1Icon from "./icons/PlasmicIcon__Ellipse1"; // plasmic-import: QKSWt9WSSI/icon
import NavbarIcon from "./icons/PlasmicIcon__Navbar"; // plasmic-import: 14ZJqMxE_W/icon
import Navbar2Icon from "./icons/PlasmicIcon__Navbar2"; // plasmic-import: Ti3y7mH8ix/icon
import Navbar3Icon from "./icons/PlasmicIcon__Navbar3"; // plasmic-import: 3qg6PMqR9b/icon

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"desktop1"}
            data-plasmic-override={overrides.desktop1}
            className={classNames(projectcss.all, sty.desktop1)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__sCp)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ofMnr
                )}
              >
                {"Hello,"}
              </div>
              <div
                data-plasmic-name={"imAkshay"}
                data-plasmic-override={overrides.imAkshay}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.imAkshay
                )}
              >
                {"I’m Akshay. "}
              </div>
              <div
                data-plasmic-name={"bcaGraduatedAndUiuxDesigner"}
                data-plasmic-override={overrides.bcaGraduatedAndUiuxDesigner}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.bcaGraduatedAndUiuxDesigner
                )}
              >
                {"BCA Graduated And UI/UX Designer "}
              </div>
              <Ellipse2Icon
                className={classNames(projectcss.all, sty.svg__cvIqk)}
                role={"img"}
              />
            </div>
            <div
              data-plasmic-name={"logo"}
              data-plasmic-override={overrides.logo}
              className={classNames(projectcss.all, sty.logo)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__kX6E
                )}
              >
                {"Port Folio"}
              </div>
            </div>
            <div
              data-plasmic-name={"navbar"}
              data-plasmic-override={overrides.navbar}
              className={classNames(projectcss.all, sty.navbar)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"frame1"}
                data-plasmic-override={overrides.frame1}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame1)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4XmUf
                  )}
                >
                  {"Home"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__iiR4I
                  )}
                >
                  {"About"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__qsMh
                  )}
                >
                  {"Project"}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mgIkv
                  )}
                >
                  {"Contact me"}
                </div>
              </p.Stack>
              <Ellipse1Icon
                className={classNames(projectcss.all, sty.svg__c0Qk)}
                role={"img"}
              />

              <div
                data-plasmic-name={"rectangle1"}
                data-plasmic-override={overrides.rectangle1}
                className={classNames(projectcss.all, sty.rectangle1)}
              />
            </div>
            <div
              data-plasmic-name={"button"}
              data-plasmic-override={overrides.button}
              className={classNames(projectcss.all, sty.button)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"frame2"}
                data-plasmic-override={overrides.frame2}
                hasGap={true}
                className={classNames(projectcss.all, sty.frame2)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___1Ei4D
                  )}
                >
                  {"Download CV"}
                </div>
              </p.Stack>
            </div>
            <div
              data-plasmic-name={"portfolio"}
              data-plasmic-override={overrides.portfolio}
              className={classNames(projectcss.all, sty.portfolio)}
            >
              <div
                data-plasmic-name={"desktop2"}
                data-plasmic-override={overrides.desktop2}
                className={classNames(projectcss.all, sty.desktop2)}
              >
                <div
                  data-plasmic-name={"text2"}
                  data-plasmic-override={overrides.text2}
                  className={classNames(projectcss.all, sty.text2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___3T6Hq
                    )}
                  >
                    {"Hello,"}
                  </div>
                  <div
                    data-plasmic-name={"imAkshay2"}
                    data-plasmic-override={overrides.imAkshay2}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.imAkshay2
                    )}
                  >
                    {"I’m Akshay. "}
                  </div>
                  <div
                    data-plasmic-name={"bcaGraduatedAndUiuxDesigner2"}
                    data-plasmic-override={
                      overrides.bcaGraduatedAndUiuxDesigner2
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.bcaGraduatedAndUiuxDesigner2
                    )}
                  >
                    {"BCA Graduated And UI/UX Designer "}
                  </div>
                  <Ellipse2Icon
                    className={classNames(projectcss.all, sty.svg__lcDTp)}
                    role={"img"}
                  />
                </div>
                <div
                  data-plasmic-name={"logo2"}
                  data-plasmic-override={overrides.logo2}
                  className={classNames(projectcss.all, sty.logo2)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kpuEd
                    )}
                  >
                    {"Port Folio"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"logo3"}
                  data-plasmic-override={overrides.logo3}
                  className={classNames(projectcss.all, sty.logo3)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kaZjX
                    )}
                  >
                    {"About Me"}
                  </div>
                </div>
                <NavbarIcon
                  className={classNames(projectcss.all, sty.svg___6MmHq)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"button2"}
                  data-plasmic-override={overrides.button2}
                  className={classNames(projectcss.all, sty.button2)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame3"}
                    data-plasmic-override={overrides.frame3}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame3)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___9UmLw
                      )}
                    >
                      {"Download CV"}
                    </div>
                  </p.Stack>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"portfolio2"}
              data-plasmic-override={overrides.portfolio2}
              className={classNames(projectcss.all, sty.portfolio2)}
            >
              <div
                data-plasmic-name={"desktop3"}
                data-plasmic-override={overrides.desktop3}
                className={classNames(projectcss.all, sty.desktop3)}
              >
                <div
                  data-plasmic-name={"text3"}
                  data-plasmic-override={overrides.text3}
                  className={classNames(projectcss.all, sty.text3)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__a2Ez8
                    )}
                  >
                    {"Hello,"}
                  </div>
                  <div
                    data-plasmic-name={"imAkshay3"}
                    data-plasmic-override={overrides.imAkshay3}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.imAkshay3
                    )}
                  >
                    {"I’m Akshay. "}
                  </div>
                  <div
                    data-plasmic-name={"bcaGraduatedAndUiuxDesigner3"}
                    data-plasmic-override={
                      overrides.bcaGraduatedAndUiuxDesigner3
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.bcaGraduatedAndUiuxDesigner3
                    )}
                  >
                    {"BCA Graduated And UI/UX Designer "}
                  </div>
                  <Ellipse2Icon
                    className={classNames(projectcss.all, sty.svg__foMm7)}
                    role={"img"}
                  />
                </div>
                <div
                  data-plasmic-name={"logo4"}
                  data-plasmic-override={overrides.logo4}
                  className={classNames(projectcss.all, sty.logo4)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___33V3
                    )}
                  >
                    {"Port Folio"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"logo5"}
                  data-plasmic-override={overrides.logo5}
                  className={classNames(projectcss.all, sty.logo5)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___0Irim
                    )}
                  >
                    {"PROJECTS"}
                  </div>
                </div>
                <Navbar2Icon
                  className={classNames(projectcss.all, sty.svg___7L8Zm)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"button3"}
                  data-plasmic-override={overrides.button3}
                  className={classNames(projectcss.all, sty.button3)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame4"}
                    data-plasmic-override={overrides.frame4}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame4)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hkfch
                      )}
                    >
                      {"Download CV"}
                    </div>
                  </p.Stack>
                </div>
              </div>
            </div>
            <div
              data-plasmic-name={"portfolio3"}
              data-plasmic-override={overrides.portfolio3}
              className={classNames(projectcss.all, sty.portfolio3)}
            >
              <div
                data-plasmic-name={"desktop4"}
                data-plasmic-override={overrides.desktop4}
                className={classNames(projectcss.all, sty.desktop4)}
              >
                <div
                  data-plasmic-name={"text4"}
                  data-plasmic-override={overrides.text4}
                  className={classNames(projectcss.all, sty.text4)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lq9F
                    )}
                  >
                    {"Hello,"}
                  </div>
                  <div
                    data-plasmic-name={"imAkshay4"}
                    data-plasmic-override={overrides.imAkshay4}
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.imAkshay4
                    )}
                  >
                    {"I’m Akshay. "}
                  </div>
                  <div
                    data-plasmic-name={"bcaGraduatedAndUiuxDesigner4"}
                    data-plasmic-override={
                      overrides.bcaGraduatedAndUiuxDesigner4
                    }
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.bcaGraduatedAndUiuxDesigner4
                    )}
                  >
                    {"BCA Graduated And UI/UX Designer "}
                  </div>
                  <Ellipse2Icon
                    className={classNames(projectcss.all, sty.svg__fsbvu)}
                    role={"img"}
                  />
                </div>
                <div
                  data-plasmic-name={"logo6"}
                  data-plasmic-override={overrides.logo6}
                  className={classNames(projectcss.all, sty.logo6)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__hgmr3
                    )}
                  >
                    {"Port Folio"}
                  </div>
                </div>
                <div
                  data-plasmic-name={"logo7"}
                  data-plasmic-override={overrides.logo7}
                  className={classNames(projectcss.all, sty.logo7)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oo8Lz
                    )}
                  >
                    {"CONTACT ME"}
                  </div>
                </div>
                <Navbar3Icon
                  className={classNames(projectcss.all, sty.svg__xInGx)}
                  role={"img"}
                />

                <div
                  data-plasmic-name={"button4"}
                  data-plasmic-override={overrides.button4}
                  className={classNames(projectcss.all, sty.button4)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"frame5"}
                    data-plasmic-override={overrides.frame5}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.frame5)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vQqsh
                      )}
                    >
                      {"Download CV"}
                    </div>
                  </p.Stack>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "desktop1",
    "imAkshay",
    "bcaGraduatedAndUiuxDesigner",
    "logo",
    "navbar",
    "frame1",
    "rectangle1",
    "button",
    "frame2",
    "portfolio",
    "desktop2",
    "text2",
    "imAkshay2",
    "bcaGraduatedAndUiuxDesigner2",
    "logo2",
    "logo3",
    "button2",
    "frame3",
    "portfolio2",
    "desktop3",
    "text3",
    "imAkshay3",
    "bcaGraduatedAndUiuxDesigner3",
    "logo4",
    "logo5",
    "button3",
    "frame4",
    "portfolio3",
    "desktop4",
    "text4",
    "imAkshay4",
    "bcaGraduatedAndUiuxDesigner4",
    "logo6",
    "logo7",
    "button4",
    "frame5"
  ],

  desktop1: [
    "desktop1",
    "imAkshay",
    "bcaGraduatedAndUiuxDesigner",
    "logo",
    "navbar",
    "frame1",
    "rectangle1",
    "button",
    "frame2",
    "portfolio",
    "desktop2",
    "text2",
    "imAkshay2",
    "bcaGraduatedAndUiuxDesigner2",
    "logo2",
    "logo3",
    "button2",
    "frame3",
    "portfolio2",
    "desktop3",
    "text3",
    "imAkshay3",
    "bcaGraduatedAndUiuxDesigner3",
    "logo4",
    "logo5",
    "button3",
    "frame4",
    "portfolio3",
    "desktop4",
    "text4",
    "imAkshay4",
    "bcaGraduatedAndUiuxDesigner4",
    "logo6",
    "logo7",
    "button4",
    "frame5"
  ],

  imAkshay: ["imAkshay"],
  bcaGraduatedAndUiuxDesigner: ["bcaGraduatedAndUiuxDesigner"],
  logo: ["logo"],
  navbar: ["navbar", "frame1", "rectangle1"],
  frame1: ["frame1"],
  rectangle1: ["rectangle1"],
  button: ["button", "frame2"],
  frame2: ["frame2"],
  portfolio: [
    "portfolio",
    "desktop2",
    "text2",
    "imAkshay2",
    "bcaGraduatedAndUiuxDesigner2",
    "logo2",
    "logo3",
    "button2",
    "frame3"
  ],

  desktop2: [
    "desktop2",
    "text2",
    "imAkshay2",
    "bcaGraduatedAndUiuxDesigner2",
    "logo2",
    "logo3",
    "button2",
    "frame3"
  ],

  text2: ["text2", "imAkshay2", "bcaGraduatedAndUiuxDesigner2"],
  imAkshay2: ["imAkshay2"],
  bcaGraduatedAndUiuxDesigner2: ["bcaGraduatedAndUiuxDesigner2"],
  logo2: ["logo2"],
  logo3: ["logo3"],
  button2: ["button2", "frame3"],
  frame3: ["frame3"],
  portfolio2: [
    "portfolio2",
    "desktop3",
    "text3",
    "imAkshay3",
    "bcaGraduatedAndUiuxDesigner3",
    "logo4",
    "logo5",
    "button3",
    "frame4"
  ],

  desktop3: [
    "desktop3",
    "text3",
    "imAkshay3",
    "bcaGraduatedAndUiuxDesigner3",
    "logo4",
    "logo5",
    "button3",
    "frame4"
  ],

  text3: ["text3", "imAkshay3", "bcaGraduatedAndUiuxDesigner3"],
  imAkshay3: ["imAkshay3"],
  bcaGraduatedAndUiuxDesigner3: ["bcaGraduatedAndUiuxDesigner3"],
  logo4: ["logo4"],
  logo5: ["logo5"],
  button3: ["button3", "frame4"],
  frame4: ["frame4"],
  portfolio3: [
    "portfolio3",
    "desktop4",
    "text4",
    "imAkshay4",
    "bcaGraduatedAndUiuxDesigner4",
    "logo6",
    "logo7",
    "button4",
    "frame5"
  ],

  desktop4: [
    "desktop4",
    "text4",
    "imAkshay4",
    "bcaGraduatedAndUiuxDesigner4",
    "logo6",
    "logo7",
    "button4",
    "frame5"
  ],

  text4: ["text4", "imAkshay4", "bcaGraduatedAndUiuxDesigner4"],
  imAkshay4: ["imAkshay4"],
  bcaGraduatedAndUiuxDesigner4: ["bcaGraduatedAndUiuxDesigner4"],
  logo6: ["logo6"],
  logo7: ["logo7"],
  button4: ["button4", "frame5"],
  frame5: ["frame5"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    desktop1: makeNodeComponent("desktop1"),
    imAkshay: makeNodeComponent("imAkshay"),
    bcaGraduatedAndUiuxDesigner: makeNodeComponent(
      "bcaGraduatedAndUiuxDesigner"
    ),
    logo: makeNodeComponent("logo"),
    navbar: makeNodeComponent("navbar"),
    frame1: makeNodeComponent("frame1"),
    rectangle1: makeNodeComponent("rectangle1"),
    button: makeNodeComponent("button"),
    frame2: makeNodeComponent("frame2"),
    portfolio: makeNodeComponent("portfolio"),
    desktop2: makeNodeComponent("desktop2"),
    text2: makeNodeComponent("text2"),
    imAkshay2: makeNodeComponent("imAkshay2"),
    bcaGraduatedAndUiuxDesigner2: makeNodeComponent(
      "bcaGraduatedAndUiuxDesigner2"
    ),
    logo2: makeNodeComponent("logo2"),
    logo3: makeNodeComponent("logo3"),
    button2: makeNodeComponent("button2"),
    frame3: makeNodeComponent("frame3"),
    portfolio2: makeNodeComponent("portfolio2"),
    desktop3: makeNodeComponent("desktop3"),
    text3: makeNodeComponent("text3"),
    imAkshay3: makeNodeComponent("imAkshay3"),
    bcaGraduatedAndUiuxDesigner3: makeNodeComponent(
      "bcaGraduatedAndUiuxDesigner3"
    ),
    logo4: makeNodeComponent("logo4"),
    logo5: makeNodeComponent("logo5"),
    button3: makeNodeComponent("button3"),
    frame4: makeNodeComponent("frame4"),
    portfolio3: makeNodeComponent("portfolio3"),
    desktop4: makeNodeComponent("desktop4"),
    text4: makeNodeComponent("text4"),
    imAkshay4: makeNodeComponent("imAkshay4"),
    bcaGraduatedAndUiuxDesigner4: makeNodeComponent(
      "bcaGraduatedAndUiuxDesigner4"
    ),
    logo6: makeNodeComponent("logo6"),
    logo7: makeNodeComponent("logo7"),
    button4: makeNodeComponent("button4"),
    frame5: makeNodeComponent("frame5"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
